server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      #dialect: org.hibernate.dialect.PostgreSQLDialect
      #jdbc:
    #    lob.non-contextual-creation: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #show_sql: true
  #Cor do terminal
  #output:
    #ansi:
      #enabled: ALWAYS

        
logging:
  level:
    '[br.com.mcb.ead]': DEBUG
    #'[br.com.mcb.ead]': TRACE
    #root: DEBUG
    #org.springframework.web: DEBUG
    
ead:
  api:
    url:
      course: 'http://ead-course-service'
      
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost
    