server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      #dialect: org.hibernate.dialect.PostgreSQLDialect
      #jdbc:
    #    lob.non-contextual-creation: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #show_sql: true
